# Generated by Django 4.1.3 on 2022-11-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salesman_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25, verbose_name='Категория')),
                ('manufacturer', models.CharField(max_length=40, verbose_name='Производитель')),
                ('name', models.CharField(max_length=16, verbose_name='Наименование')),
                ('unit', models.IntegerField(verbose_name='Единица измерения')),
                ('barcode', models.IntegerField(verbose_name='Штрих-код')),
            ],
        ),
    ]
