# Generated by Django 4.1.3 on 2022-11-11 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salesman_feedback',
            new_name='Products',
        ),
    ]
