# Generated by Django 4.1.3 on 2022-11-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_salesman_feedback_products'),
    ]

    operations = [
    ]
