# Generated by Django 4.1.3 on 2022-11-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221111_2232'),
    ]

    operations = [
    ]
