# Generated by Django 4.1.3 on 2022-11-11 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221111_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='products',
            name='unit',
        ),
    ]
