# Generated by Django 4.1.3 on 2022-11-11 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_products_barcode_remove_products_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
